# Generated by Django 5.0.2 on 2024-03-15 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='fixed_expense',
            new_name='fix_expense',
        ),
    ]
