# Generated by Django 5.0.2 on 2024-03-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0002_rename_fixed_expense_expense_fix_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='exp_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
