# Generated by Django 5.0.2 on 2024-03-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0003_expense_exp_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='price',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='time',
            new_name='goalDeadline',
        ),
        migrations.AddField(
            model_name='goal',
            name='goal_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
