# Generated by Django 5.0.2 on 2024-03-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0004_rename_price_goal_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='start_time',
            field=models.DateField(),
        ),
    ]
