# Generated by Django 4.2.6 on 2024-03-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0006_expense_user_goal_user_salary_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='user',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='salary',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
