# Generated by Django 4.2.6 on 2024-03-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0007_alter_expense_user_alter_salary_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
