# Generated by Django 5.0.2 on 2024-03-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0008_alter_goal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='sal_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
